version: "3"

services:
  service1:
    build:
      context: ./service1
    ports:
      - "9001:9001"

  service2:
    build:
      context: ./service2
    depends_on:
      - service1
    ports:
      - "9002:9002"
